on: [push, pull_request]
name: Unit Testing
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Setup environment
        run: |
          # Changing into a different directory to avoid polluting go.sum with "go get"
          cd "$(mktemp -d)"
          go mod init unit_tests

          go install golang.org/x/tools/cmd/goimports@latest

      - name: Run go vet
        run: |
          go vet ./...

      - name: Run unit tests
        run: |
          go test -v ./...

      - name: Check for formatting
        run:
          ./script/format
